[package]
name = "tic_tac_toe"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
opt-level = 3

[dependencies]
anyhow = "1.0.69"
rand = "0.8.5"
sdl2 = { version = "0.35.2", features = ["ttf"] }
